### ISSUE TITLE
Docker build failed 

### ISSUE THREAD

**Issue by astha-rigi** [kodermax/kubectl-aws-eks#40] opened 2023-11-29 12:23 UTC
Due to recent changes done 2 hours ago, github action is failing with below:

 ```
ERROR: failed to solve: process "/bin/sh -c curl -sL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl &&     curl -sL -o /usr/bin/aws-iam-authenticator $(curl -s https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest | jq -r ' .assets[] | select(.name | contains(\"linux_amd64\")    )' | jq -r '.browser_download_url')  &&     chmod +x /usr/bin/aws-iam-authenticator &&     chmod +x /usr/bin/kubectl" did not complete successfully: exit code: 2
Error: Docker build failed with exit code 1

```

**Comment by alisonfrancisco** [comment] 2023-11-29 12:37
same here

**Comment by flxdot** [comment] 2023-11-29 12:43
duplicate of #38

**Comment by christallire** [comment] 2023-11-29 13:12
omg. not again.

**Comment by CleberSilva93** [comment] 2023-11-29 13:40
Validate whether you are using kodermax/kubectl-aws-eks@master or kodermax/kubectl-aws-eks@main. If you are currently using kodermax/kubectl-aws-eks@master, switch to kodermax/kubectl-aws-eks@main.

For me, its work

**Comment by astha-rigi** [comment] 2023-11-29 14:04
that works, thanks

**Comment by kodermax** [comment] 2023-11-29 14:09
The problem happened on the aws-iam-authenticator side; in the latest version they did not prepare packages for Linux systems. I also updated the master branch.

**Closed by kodermax** 2023-11-29 14:09 UTC
